[package]
name = "msx-editor"
version = "1.1.1"
description = "MSXJuanEditor — MSX1 tile, screen and sprite editor"
edition = "2021"

[lib]
name = "msx_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
